
<footer>
 <!--	<div class="row">
 <div class="column">
	<div class="footer-links">
		<a href="projects.php">Projects</a>
		<a href="about.php">Our Team</a>
		<a href="services.php">Our Services</a>
	</div>
	

</div>
<div class="column">
	<div class="footer-links">
		
		<a href="mailto:support@turnyur.com">Email Us</a>
		<a href="contact-us.php">Feedback</a>
		<a href="">Test Link</a>
	</div>
	

</div>
<div class="column">
	<div class="footer-links">
		<a href="www.facebook.com/turnyurtechnologies">Facebook</a>
		<a href="www.twitter.com/turnyurtechnologies">Twitter</a>
		<a href="www.linkedn.com/turnyurtechnologies">Linkedn</a>

	</div> 
	

</div> 
</div>-->

<p><?php echo date('Y');?> <strong>Andrah&reg;</strong> Fish Farm Soft </p>
</footer>
<!-- <button id="goUpButton" class="fa fa-arrow-up" title="Navigate To Top"><button> -->
	<img src="assets/images/interface/up21.png" id="goUpButton" title="Navigate To Top" >


</body> 
 <script src="assets/js/jquery-3.2.1.min.js"></script>
 <script src="assets/js/validate-data.js"></script>
 <script src="assets/js/init.js"></script>
 
 
 


</html> 