<div class="hero-image">
  <div class="hero-text">
    <h1 style="font-size:30px">COMPLETE TRACEABILITY</h1>
    <p>Know which types of feed or feed batches have been used for each batch of fish, track the use of medicaments, respond quickly and accurately to customer requests, comply with standards. Follow your fish from input to harvest.</p>
    <!-- <button>GET STARTED</button> -->
  </div>
</div>

<!-- <p>&nbsp;</p> -->
