<div class="slideshow-container">

<div class="mySlides fade">
  <div class="numbertext">&nbsp;</div>
  <img src="assets/images/bram-naus-221602-unsplash.jpg" style="width:100%">
 <div class="text" style="color: white">
    <h2>Andrah Fish Farm Management Software</h2>
    <p>A cost effective software solution for acquaculture production control that will pay for itself! Take control of your business with a state-of-the-art, easy to use system that continually measures and tracks your fish production in real time.
    <br>Be proactive, identify poor perfomance before it becomes a problem. Improve production management, efficiency and visibility.</p> </div>
</div>

<div class="mySlides fade">
  <div class="numbertext">&nbsp;</div>
  <img src="assets/images/filip-gielda-94858-unsplash.jpg" style="width:100%">
   <div class="text" style="color: white">
    <h2>Cloud Based Fish Farm Management Software</h2>
    <p> ► Low-cost acquaculture software</p>
    <p> ► Real Time Data Capture</p>
    <p> ► Improve Feeding</p>
    <p> ► Reduce Cost of Running your fish farm</p>
    <p> ► Complete Traceability</p>
    <p> ► Amazing Reports and Visualizations</p>
  </div>
</div>

<div class="mySlides fade">
  <div class="numbertext">&nbsp;</div>
  <img src="assets/images/artificial-photography-119298-unsplash.jpg" style="width:100%">
  <div class="text" style="color: white">
    <h2>Access from Everywhere</h2>
    <p>Andrah enables you to access real-time, updated, information from any place you go, using any device such as desktop, laptop, tablet or mobile phone. Get valuable insights anytime, anywhere, make faster, more informed decisions, remain in touch with your acquaculture's reality regardless of your location. You can access all these functionalities using just a web browser or your mobile phone!</p>

  </div>
</div>

<!--<a class="prev" >&#10094;</a>
<a class="next">&#10095;</a> -->
<div style="text-align:center">
  <span class="dot" onclick="currentSlide(1)"></span> 
  <span class="dot" onclick="currentSlide(2)"></span> 
  <span class="dot" onclick="currentSlide(3)"></span> 
</div>
</div>
<br>

